<a href="https://colab.research.google.com/github/JesseNjenga/ChurnWiz-Data-Driven-Customer-Churn-Analysis-with-Python-Power-BI/blob/main/TelecomChurn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

#load dataset

data = pd.read_excel('Dataset.xlsx')

In [3]:
#overview of the data

data.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,numAdminTickets,numTechTickets,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,0,0,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,No,No,One year,No,Mailed check,56.95,1889.5,0,0,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,0,0,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,0,3,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,0,0,Yes

In [5]:
#structure and composition of the dataframe
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 23 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  numAdminTickets   7043 non-null   int64
 21  numTechTickets    7043 non-null   int64
 22  Churn             7043 non-null   object
dtypes: float64(1), int64(4), object(18)
memory usage: 1.2+ MB


Data has no null values.

In [6]:
#check for duplicates

duplicates = data[data['customerID'].duplicated(keep=False)]

if not duplicates.empty:
    print("Duplicated customer IDs:")
    print(duplicates['customerID'].unique())
else:
    print("There are no duplicates in the 'customerID' column.")

There are no duplicates in the 'customerID' column.

The data does not have duplicated clients.
We proceed check the datatypes accuracy for each column.

In [7]:
#change Totalcharges datatype to float

data['TotalCharges'] = pd.to_numeric(data['TotalCharges'], errors='coerce')

For columns Partner, Dependents, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies I will convert the datatypes to boolen. The first step is to convert columns values to Yes & No, then convert the data to 1 & 0 for better manipulation using powerBI.

In [9]:
#unique values in columns

columns_to_check = ["MultipleLines", "OnlineSecurity", "OnlineBackup", "DeviceProtection", "TechSupport", "StreamingTV", "StreamingMovies"]

for column in columns_to_check:
    unique_values = data[column].unique()
    print(f"Unique values in {column}:")
    print(unique_values)
    print()

Unique values in MultipleLines:
['No phone service' 'No' 'Yes']

Unique values in OnlineSecurity:
['No' 'Yes' 'No internet service']

Unique values in OnlineBackup:
['Yes' 'No' 'No internet service']

Unique values in DeviceProtection:
['No' 'Yes' 'No internet service']

Unique values in TechSupport:
['No' 'Yes' 'No internet service']

Unique values in StreamingTV:
['No' 'Yes' 'No internet service']

Unique values in StreamingMovies:
['No' 'Yes' 'No internet service']

In [11]:
#Replacing the values with "NO"

data['MultipleLines'] = data['MultipleLines'].replace('No phone service', 'No')

columns_to_replace = ["OnlineSecurity", "OnlineBackup", "DeviceProtection", "TechSupport", "StreamingTV", "StreamingMovies"]

for column in columns_to_replace:
    data[column] = data[column].replace('No internet service', 'No')

In [12]:
#replace column values 'Ýes' & 'No' with 1 & 0

columns_to_replace = ["Partner", "Dependents", "PhoneService", "MultipleLines", "InternetService",
                      "OnlineSecurity", "OnlineBackup", "DeviceProtection", "TechSupport",
                      "StreamingTV", "StreamingMovies", "PaperlessBilling", "Churn"]

replacement_mapping = {'Yes': 1, 'No': 0}

data[columns_to_replace] = data[columns_to_replace].replace(replacement_mapping)

In [13]:
# Convert the columns to boolean

data[columns_to_replace] = data[columns_to_replace].astype(bool)

In [14]:
#export data to excel for visualization in PowerBI

data.to_excel('telecom.xlsx', index=False)